### ISSUE TITLE
simpleminer

### ISSUE THREAD

**Issue by StasKoval** [lucasjones/node-boolberry-pool#1]
Sometimes got message

2014-Jun-07 01:45:28.885993 ERROR /root/boolberry/contrib/epee/include/storages/http_abstract_invoke.h:112[bool epee::net_utils::invoke_http_json_rpc(const string&, const string&, t_request&, t_response&, t_transport&, unsigned int, const string&, const string&) [with t_request = mining::COMMAND_RPC_SUBMITSHARE::request; t_response = mining::COMMAND_RPC_SUBMITSHARE::response; t_transport = epee::net_utils::http::http_simple_client; std::string = std::basic_string<char>]]RPC call of "submit" returned error: -1, message: Low difficulty share

**Comment by lucasjones** [comment]
That would have happened when simpleminer submitted a stale share.
I have changed the message to `Job expired`, and stopped stale shares being detected as low difficulty with @a74e2dd367f67cee36f50990168bfaab7470c6ba.
